name: CI
on:
  push:
    branches: 
      - '*/*'
  pull_request:
    branches: 
      - '*/*' 
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Use Node.js 18.12
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.0
          cache: 'pnpm'
      - name: Install dependencies using pnpm (resolving lockfile and deps)
        run: pnpm install --no-frozen-lockfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AMPLIFY.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AMPLIFY.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Next.js app
        run: npx serverless
